const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPosToObject
	];
};
self.C3_JsPropNameTable = [
	{ДвижениеК: 0},
	{"8Направлений": 0},
	{maincharacter: 0},
	{Мышь: 0},
	{backgroundtext: 0},
	{text: 0},
	{Клавиатура: 0},
	{ID: 0},
	{TriggerDialogue: 0},
	{indicator_of_willingness_to_engage_in_dialogue: 0},
	{backgroundtextchoice_3: 0},
	{backgroundtextchoice_2: 0},
	{backgroundtextchoice_1: 0},
	{text_choice1: 0},
	{text_choice2: 0},
	{text_choice3: 0},
	{Текст: 0},
	{Scale: 0},
	{Твёрдый: 0},
	{block2: 0},
	{block1: 0},
	{man_1: 0},
	{wooden_floor: 0},
	{block3: 0},
	{Trigger_location: 0},
	{Аудио: 0},
	{PaperNote: 0},
	{man_2: 0},
	{Спрайт: 0},
	{man_3: 0},
	{Спрайт2: 0},
	{Текст2: 0},
	{Текст3: 0},
	{text_speech: 0},
	{timetext: 0},
	{Scale_empathy: 0},
	{Scale_empathy_2: 0},
	{Number_Location: 0},
	{TriggerDialogueChoice: 0},
	{correct_choice_1: 0},
	{correct_choice_2: 0},
	{correct_choice_3: 0}
];

self.InstanceType = {
	maincharacter: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	backgroundtext: class extends self.IWorldInstance {},
	text: class extends self.ITextInstance {},
	Клавиатура: class extends self.IInstance {},
	TriggerDialogue: class extends self.ISpriteInstance {},
	indicator_of_willingness_to_engage_in_dialogue: class extends self.ISpriteInstance {},
	backgroundtextchoice_3: class extends self.IWorldInstance {},
	backgroundtextchoice_2: class extends self.IWorldInstance {},
	backgroundtextchoice_1: class extends self.IWorldInstance {},
	text_choice1: class extends self.ITextInstance {},
	text_choice2: class extends self.ITextInstance {},
	text_choice3: class extends self.ITextInstance {},
	Текст: class extends self.ITextInstance {},
	Scale: class extends self.ISpriteInstance {},
	block2: class extends self.IWorldInstance {},
	block1: class extends self.IWorldInstance {},
	man_1: class extends self.ISpriteInstance {},
	wooden_floor: class extends self.ITiledBackgroundInstance {},
	block3: class extends self.ISpriteInstance {},
	Trigger_location: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	PaperNote: class extends self.ISpriteInstance {},
	man_2: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	man_3: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	Текст3: class extends self.ITextInstance {}
}